# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
#  STARSHIP â€” Fedora Capsule Theme (Official Colors)
#  Palette: Dark Fedora Blue â†’ Fedora Blue â†’ New Fedora Blue
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€


format = """
[](#48b9c7)\
[ ïŒª $username@$hostname ](bg:#48b9c7 fg:#FFFFFF)\
[î‚°](fg:#48b9c7 bg:#6cc7d2)\
[ ï» $directory](bg:#6cc7d2 fg:#FFFFFF)\
[î‚´](fg:#6cc7d2)\
$character
"""

right_format = """$git_branch$git_status | $cmd_duration"""

[username]
show_always = true
format = "$user"
style_user = "bg:#73BA25 fg:#FFFFFF"

[directory]
truncate_to_repo = true
truncation_length = 2
style = "bg:#6cc7d2 fg:#FFFFFF"
read_only = "ğŸ”’"
read_only_style = "bg:#3C6EB4 fg:#FFFFFF"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "bold yellow"

[python]
format = "îˆµ [$version]($style)"
style = "bg:#A07CBC fg:#0E1116"
disabled = false

[time]
disabled = false
time_format = "ï€— %H:%M"
style = "bold cyan"
format = "[$time]($style)"


[cmd_duration]
min_time = 0
format = "ğŸ•’ [$duration](bold yellow)"


[character]
success_symbol = "[â¯](bold #faa41a)"
error_symbol   = "[â¯](bold red)"

[hostname]
ssh_only = false
format = "$hostname"
style = "bg:#294172 fg:#FFFFFF"
disabled = false
